# -*- coding: utf-8 -*-
"""Data Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bt7gDq2aGuQL8bcDsukiQL8wWXRdx4et
"""

# -*- coding: utf-8 -*-
"""Analysis_ on_abhinav_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bjhJYfGTunXOHWTQM8FM_zHVre6UG4OK
"""

!pip install optuna
import optuna
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import random
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Activation, Dropout, Flatten, Input, Dense, concatenate
from sklearn.metrics import accuracy_score, precision_score, recall_score, r2_score, mean_squared_error
from tensorflow.keras.models import Model, Sequential, load_model
from sklearn.model_selection import train_test_split
from google.colab import drive
drive.mount('/content/drive')

!pip install latex
import latex
! sudo apt-get install texlive-latex-recommended
! sudo apt install texlive-latex-extra
! sudo apt install dvipng
! sudo apt install cm-super
from numpy import arange
from numpy.random import rand
from matplotlib import pyplot
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.ticker import AutoMinorLocator
import matplotlib.pyplot as plt
from numpy import arange
from numpy.random import rand
from matplotlib import pyplot
import numpy as np
from matplotlib.ticker import AutoMinorLocator
import matplotlib.pyplot as plt
from matplotlib import rc
import matplotlib.gridspec as gridspec
from google.colab import files
import matplotlib.ticker as ticker
from collections import OrderedDict
linestyles_dict = OrderedDict(
    [('solid',               (0, ())),
     ('loosely dotted',      (0, (1, 10))),
     ('dotted',              (0, (1, 5))),
     ('densely dotted',      (0, (1, 1))),

     ('loosely dashed',      (0, (5, 10))),
     ('dashed',              (0, (5, 5))),
     ('densely dashed',      (0, (5, 1))),

     ('loosely dashdotted',  (0, (3, 10, 1, 10))),
     ('dashdotted',          (0, (3, 5, 1, 5))),
     ('densely dashdotted',  (0, (3, 1, 1, 1))),

     ('loosely dashdotdotted', (0, (3, 10, 1, 10, 1, 10))),
     ('dashdotdotted',         (0, (3, 5, 1, 5, 1, 5))),
     ('densely dashdotdotted', (0, (3, 1, 1, 1, 1, 1)))])
rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
#rc('font',**{'family':'sans-serif','sans-serif':['Times new roman']})
rc('text', usetex=True)

"""##Data"""

#path = "/content/drive/My Drive/ml-task1-dataset.csv"
path = "/content/drive/My Drive/ML-Dataset/ds_train_n1.csv"

np.random.seed(1)
tf.random.set_seed(2)

def compute_rse(y,yhat):
  #y = y.ravel()
  yhat = yhat.ravel()
  yhat = tf.cast(yhat, dtype=tf.float64)
  mu = np.mean(y)
  return np.sqrt(np.sum((y-yhat)**2))/np.sqrt(np.sum((y-mu)**2))
def compute_smape(y,yhat):
  #y = y.ravel()
  #yhat = yhat.ravel()
  n = len(y)
  nr = np.abs(y - yhat)
  dr = 0.5*(np.abs(y) + np.abs(yhat))
  return (100./n)*np.sum(nr/dr)

def encoder(src_data, tar_data, feature_name):
  src_data_c = pd.DataFrame()
  tar_data_c = pd.DataFrame()
  for pos in range(len(src_data)):
    row = src_data[pos:pos+1]
    s = str(row[[feature_name]])
    s = s.strip()
    arg_array = s.split(" ")
    arg_array.pop(0)
    arg_array.remove('')
    l =[]
    idx = 0
    while idx < (len(arg_array)):
      arg = arg_array[idx]
      #print(arg)
      if arg not in tar_data_c.columns:
        tar_data_c[arg]=0
      if re.match('-\S+', arg):
        l.append(arg)
        if idx+1 < len(arg_array):
          if str(arg_array[idx+1]).isnumeric():
            src_data_c.at[pos, arg]= float(arg_array[idx+1])
          else:
            src_data_c.at[pos, arg]= str(arg_array[idx+1])
          idx = idx + 2
        else:
          src_data_c.at[pos, arg]= 1
          idx = idx + 1
      else:
        src_data_c.at[pos,"argPath"] = arg
        idx = idx + 1
        #print("in third block")
  for pos in range(len(tar_data)):
    row = tar_data[pos:pos+1]
    s = str(row[[feature_name]])
    s = s.strip()
    arg_array = s.split(" ")
    arg_array.pop(0)
    arg_array.remove('')
    l =[]
    idx = 0
    while idx < (len(arg_array)):
      arg = arg_array[idx]
      #print(arg)
      if arg not in src_data_c.columns:
        src_data_c[arg]=0
      if re.match('-\S+', arg):
        l.append(arg)
        if idx+1 < len(arg_array):
          if str(arg_array[idx+1]).isnumeric():
            tar_data_c.at[pos, arg]= float(arg_array[idx+1])
          else:
            tar_data_c.at[pos, arg]= str(arg_array[idx+1])
          idx = idx + 2
        else:
          tar_data_c.at[pos, arg]= 1
          idx = idx + 1
      else:
        tar_data_c.at[pos,"argPath"] = arg
        idx = idx + 1
        #print("in third block")
  return src_data_c, tar_data_c
  #args = row[["args"]]
  """
  print(len(arg_array))
  print(arg_array)
  print(l)
  """
  """
  for name in l:
    if name not in data.columns:
      data[name]=0
      print("column added")
  """

import re
def encoder(src_data, tar_data, val_data, feature_name):
  src_data_c = pd.DataFrame()
  tar_data_c = pd.DataFrame()
  val_data_c = pd.DataFrame()
  for pos in range(len(src_data)):
    row = src_data[pos:pos+1]
    s = str(row[[feature_name]])
    s = s.strip()
    arg_array = s.split(" ")
    arg_array.pop(0)
    arg_array.remove('')
    l =[]
    idx = 0
    while idx < (len(arg_array)):
      arg = arg_array[idx]
      #print(arg)
      if arg not in tar_data_c.columns:
        tar_data_c[arg]=0
      if re.match('-\S+', arg):
        l.append(arg)
        if idx+1 < len(arg_array):
          if str(arg_array[idx+1]).isnumeric():
            src_data_c.at[pos, arg]= float(arg_array[idx+1])
          else:
            src_data_c.at[pos, arg]= str(arg_array[idx+1])
          idx = idx + 2
        else:
          src_data_c.at[pos, arg]= 1
          idx = idx + 1
      else:
        src_data_c.at[pos,"argPath"] = arg
        idx = idx + 1
        #print("in third block")
  for pos in range(len(tar_data)):
    row = tar_data[pos:pos+1]
    s = str(row[[feature_name]])
    s = s.strip()
    arg_array = s.split(" ")
    arg_array.pop(0)
    arg_array.remove('')
    l =[]
    idx = 0
    while idx < (len(arg_array)):
      arg = arg_array[idx]
      #print(arg)
      if arg not in src_data_c.columns:
        src_data_c[arg]=0
      if re.match('-\S+', arg):
        l.append(arg)
        if idx+1 < len(arg_array):
          if str(arg_array[idx+1]).isnumeric():
            tar_data_c.at[pos, arg]= float(arg_array[idx+1])
          else:
            tar_data_c.at[pos, arg]= str(arg_array[idx+1])
          idx = idx + 2
        else:
          tar_data_c.at[pos, arg]= 1
          idx = idx + 1
      else:
        tar_data_c.at[pos,"argPath"] = arg
        idx = idx + 1
        #print("in third block")
  for pos in range(len(val_data)):
    row = val_data[pos:pos+1]
    s = str(row[[feature_name]])
    s = s.strip()
    arg_array = s.split(" ")
    arg_array.pop(0)
    arg_array.remove('')
    l =[]
    idx = 0
    while idx < (len(arg_array)):
      arg = arg_array[idx]
      #print(arg)
      if arg not in src_data_c.columns:
        src_data_c[arg]=0
      if re.match('-\S+', arg):
        l.append(arg)
        if idx+1 < len(arg_array):
          if str(arg_array[idx+1]).isnumeric():
            val_data_c.at[pos, arg]= float(arg_array[idx+1])
          else:
            val_data_c.at[pos, arg]= str(arg_array[idx+1])
          idx = idx + 2
        else:
          val_data_c.at[pos, arg]= 1
          idx = idx + 1
      else:
        val_data_c.at[pos,"argPath"] = arg
        idx = idx + 1
        #print("in third block")
  return src_data_c, tar_data_c, val_data_c
  #args = row[["args"]]
  """
  print(len(arg_array))
  print(arg_array)
  print(l)
  """
  """
  for name in l:
    if name not in data.columns:
      data[name]=0
      print("column added")
  """

data = pd.read_csv(path)
data = data.drop(['PM_MATH_FLOP_CMPL', 'L1-DCACHE-LOAD-MISSES','L1-ICACHE-LOAD-MISSES'], axis = 1)
data = data.replace("?", np.nan)
data = data.dropna(axis=0)

df = data[['duration', 'BR_INS', 'LD_INS', 'SR_INS',
       'TOT_INS', 'L1_LDM', 'L1_STM', 'L2_LDM', 'L2_STM', 'FP_SINGLE',
       'FP_DOUBLE', 'ARITH', 'IO Bytes Read', 'IO Bytes Written', 'MEM_WCY', 'Overhead']].div(data.TOT_INS, axis=0)
df = pd.concat([data[["machine","app","args","REALTIME (sec)"]],df], axis=1)
data = df
data.describe()
data_metrics = data[['duration', 'BR_INS', 'LD_INS', 'SR_INS',
       'TOT_INS', 'L1_LDM', 'L1_STM', 'L2_LDM', 'L2_STM', 'FP_SINGLE',
       'FP_DOUBLE', 'ARITH', 'IO Bytes Read', 'IO Bytes Written', 'MEM_WCY',
       'REALTIME (sec)', 'Overhead']]

ruby_laghos = data.loc[(data['machine'] =="ruby") & (data['app'] == "laghos")]
corona_laghos = data.loc[(data['machine'] =="corona") & (data['app'] == "laghos")]
lassen_laghos = data.loc[(data['machine'] =="lassen") & (data['app'] == "laghos")]
quartz_laghos = data.loc[(data['machine'] =="quartz") & (data['app'] == "laghos")]

ruby_kripke = data.loc[(data['machine'] =="ruby") & (data['app'] == "kripke.exe")]
corona_kripke = data.loc[(data['machine'] =="corona") & (data['app'] == "kripke.exe")]
lassen_kripke = data.loc[(data['machine'] =="lassen") & (data['app'] == "kripke.exe")]
quartz_kripke = data.loc[(data['machine'] =="quartz") & (data['app'] == "kripke.exe")]

ruby_mv = data.loc[(data['machine'] =="ruby") & (data['app'] == "miniVite")]
corona_mv = data.loc[(data['machine'] =="corona") & (data['app'] == "miniVite")]
lassen_mv = data.loc[(data['machine'] =="lassen") & (data['app'] == "miniVite")]
quartz_mv = data.loc[(data['machine'] =="quartz") & (data['app'] == "miniVite")]
ruby_amg = data.loc[(data['machine'] =="ruby") & (data['app'] == "amg")]
corona_amg = data.loc[(data['machine'] =="corona") & (data['app'] == "amg")]
lassen_amg = data.loc[(data['machine'] =="lassen") & (data['app'] == "amg")]
quartz_amg = data.loc[(data['machine'] =="quartz") & (data['app'] == "amg")]

ruby_sw = data.loc[(data['machine'] =="ruby") & (data['app'] == "sw4lite")]
corona_sw = data.loc[(data['machine'] =="corona") & (data['app'] == "sw4lite")]
lassen_sw = data.loc[(data['machine'] =="lassen") & (data['app'] == "sw4lite")]
quartz_sw = data.loc[(data['machine'] =="quartz") & (data['app'] == "sw4lite")]
ruby_td = data.loc[(data['machine'] =="ruby") & (data['app'] == "TestDfft")]
corona_td = data.loc[(data['machine'] =="corona") & (data['app'] == "TestDfft")]
lassen_td = data.loc[(data['machine'] =="lassen") & (data['app'] == "TestDfft")]
quartz_td = data.loc[(data['machine'] =="quartz") & (data['app'] == "TestDfft")]

ruby_xb = data.loc[(data['machine'] =="ruby") & (data['app'] == "XSBench")]
corona_xb = data.loc[(data['machine'] =="corona") & (data['app'] == "XSBench")]
lassen_xb = data.loc[(data['machine'] =="lassen") & (data['app'] == "XSBench")]
quartz_xb = data.loc[(data['machine'] =="quartz") & (data['app'] == "XSBench")]
ruby_mf = data.loc[(data['machine'] =="ruby") & (data['app'] == "miniFE.x")]
corona_mf = data.loc[(data['machine'] =="corona") & (data['app'] == "miniFE.x")]
lassen_mf = data.loc[(data['machine'] =="lassen") & (data['app'] == "miniFE.x")]
quartz_mf = data.loc[(data['machine'] =="quartz") & (data['app'] == "miniFE.x")]

app_names = ["laghos","kripke","mv","amg","sw","td","xb","mf"]
for app in app_names:
  src_data1 = f"quartz_{app}"
  src_data2 = f"ruby_{app}"
  src_data3 = f"corona_{app}"
  src_data1 = src_data1.add_prefix('quartz_')
  src_data2 = src_data2.add_prefix('ruby_')
  src_data3 = src_data3.add_prefix('corona_')
  src_data1 = src_data1.rename(columns={"quartz_REALTIME (sec)": "quartz_time"})
  src_data1 = src_data1.rename(columns={"quartz_args": "args"})
  src_data2 = src_data2.rename(columns={"ruby_REALTIME (sec)": "ruby_time"})
  src_data2 = src_data2.rename(columns={"ruby_args": "args"})
  src_data3 = src_data3.rename(columns={"corona_REALTIME (sec)": "corona_time"})
  src_data3 = src_data3.rename(columns={"corona_args": "args"})
  src_data1 = src_data1.drop_duplicates(subset=['args'])
  src_data2 = src_data2.drop_duplicates(subset=['args'])
  src_data3 = src_data3.drop_duplicates(subset=['args'])
  train = pd.merge(src_data1, src_data2[['args','ruby_BR_INS',
       'ruby_LD_INS', 'ruby_SR_INS', 'ruby_TOT_INS', 'ruby_L1_LDM',
       'ruby_L1_STM', 'ruby_L2_LDM', 'ruby_L2_STM', 'ruby_FP_SINGLE',
       'ruby_FP_DOUBLE', 'ruby_ARITH', 'ruby_IO Bytes Read',
       'ruby_IO Bytes Written', 'ruby_MEM_WCY', 'ruby_time']], on=["args"], how="inner", indicator="indicator_column")
  train = pd.merge(train, src_data3[['args','corona_BR_INS',
       'corona_LD_INS', 'corona_SR_INS', 'corona_TOT_INS', 'corona_L1_LDM',
       'corona_L1_STM', 'corona_L2_LDM', 'corona_L2_STM', 'corona_FP_SINGLE',
       'corona_FP_DOUBLE', 'corona_ARITH', 'corona_IO Bytes Read',
       'corona_IO Bytes Written', 'corona_MEM_WCY', 'corona_time']], on=["args"], how="inner", indicator="indicator_column2")
  train["corona_rp"] = train["corona_time"]/train["quartz_time"]
  train["ruby_rp"] = train["ruby_time"]/train["quartz_time"]
  src_data = train.drop(["args", "corona_time", "quartz_time","ruby_time"], axis=1)
  src_data = src_data.drop(["indicator_column","indicator_column2"], axis=1)
  src_data = src_data.drop(["quartz_machine","quartz_app","quartz_duration","quartz_Overhead"], axis=1)
  src_data.to_csv(f"{app}.csv", index=False)